language: go

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
- make deps
- make restore
- export CI=TRAVIS # for gotest to force colors

deploy:
  provider: releases
  api-key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true

go: 
  - 1.8
  - 1.9

script:
  - make ci
